sonar.projectKey=shine-notes
sonar.projectName=Shine Notes
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/src

sonar.exclusions=backend/src/generated/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.test.inclusions=backend/test/**/*.test.ts,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.coverage.exclusions=backend/src/server.ts,frontend/src/main.tsx,frontend/src/setupTests.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
